In [1]:
import numpy as np

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier


X, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False, parser="pandas")
X = X / 255.0
y = np.int_(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.7)

In [2]:
mlp_clf = MLPClassifier(
    solver="lbfgs",
    verbose=10,
)

mlp_clf.fit(X_train, y_train)

 This problem is unconstrained.


RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =        79510     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.41582D+00    |proj g|=  4.79419D-02

At iterate    1    f=  1.88838D+00    |proj g|=  8.39252D-02

At iterate    2    f=  1.36393D+00    |proj g|=  6.45593D-02

At iterate    3    f=  8.80145D-01    |proj g|=  1.07684D-01

At iterate    4    f=  7.03716D-01    |proj g|=  1.85323D-01

At iterate    5    f=  6.01071D-01    |proj g|=  7.95637D-02

At iterate    6    f=  5.70435D-01    |proj g|=  3.90532D-02

At iterate    7    f=  5.47462D-01    |proj g|=  3.08738D-02

At iterate    8    f=  5.20300D-01    |proj g|=  4.45975D-02

At iterate    9    f=  5.11386D-01    |proj g|=  1.50620D-01

At iterate   10    f=  4.69836D-01    |proj g|=  3.00069D-02

At iterate   11    f=  4.53198D-01    |proj g|=  2.32219D-02

At iterate   12    f=  4.25801D-01    |proj g|=  3.60508D-02

At iterate   13    f=  4.0

MLPClassifier(solver='lbfgs', verbose=10)

In [6]:
from sklearn.metrics import confusion_matrix, balanced_accuracy_score


y_pred = mlp_clf.predict(X_test)
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))
print("Balanced Accuracy Score")
print(balanced_accuracy_score(y_test, y_pred))

Confusion Matrix
[[4781    2   15    6   10   13   30   10   24   20]
 [   0 5466   20   17   13    1    3    8   10    6]
 [  21   13 4725   24   33    4   14   32   24    6]
 [   3   10   67 4735    2   70    4   24   49   22]
 [   4   10   11    4 4605    6   20   19   12   77]
 [  20   10    9   64    8 4168   28   12   42   23]
 [  16   11   18    3   24   24 4646   11   27    0]
 [   0   23   53   19   26    9    3 4882   11   46]
 [  20   36   29   41   17   44   13    7 4524   26]
 [  16    6    2   35   90   39    4   80   29 4601]]
Balanced Accuracy Score
0.9614857809673067
